root_artifacts: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source: https://drive.google.com/uc?id=1Cddh4Z-SAsEBxhmOoT0AFPnayYe21gxV
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/


data_transformation:
  root_dir: artifacts/data_transformation
  data_dir: artifacts/data_ingestion/data/
  preprocessed_data_file: artifacts/data_transformation/